# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T6O8nPEd7B-Mh5OB9W0XTKG3CBwpdh6E
"""

print("    @@      @@   @   @@@@@@   @@@@@@   @")
print("   @  @     @ @  @   @        @        @")
print("  @@@@@@    @  @ @   @  @@@   @  @@@   @")
print(" @      @   @   @@   @    @   @    @   @")
print("@        @  @    @   @@@@@@   @@@@@@   @")
def fibonacci(n, first, second):
    fib_series = [first, second]
    print(f"Berikut urutannya : ")
    print(first)
    print(f"Berikut urutanya : ")
    print(second)
    while len(fib_series) < n:
        next_fib = fib_series[-1] + fib_series[-2]
        fib_series.append(next_fib)
        print("berikut urutannya : ")
        print(next_fib)

jumlah_bilangan = int(input("Masukkan jumlah bilangan: "))
bilangan_pertama = int(input("Masukkan bilangan pertama: "))
bilangan_kedua = int(input("Masukkan bilangan kedua: "))

fibonacci(jumlah_bilangan, bilangan_pertama, bilangan_kedua)

print("    @@      @@   @   @@@@@@   @@@@@@   @")
print("   @  @     @ @  @   @        @        @")
print("  @@@@@@    @  @ @   @  @@@   @  @@@   @")
print(" @      @   @   @@   @    @   @    @   @")
print("@        @  @    @   @@@@@@   @@@@@@   @\n")

nama = input("Nama : ")

jamKerja = int(input("Jam masuk kerja : "))

gajiPerhari = 175000

if jamKerja >=6 and jamKerja <= 12:
    print(f"selamat pagi {nama}\n")

elif jamKerja >= 12 and jamKerja <= 15 :
    print(f"selamat siang {nama}\n")

elif jamKerja >= 15 and jamKerja <= 18:
    print(f"selamat sore {nama}\n")

elif jamKerja >= 18 and jamKerja <= 24:
    print(f"selamat malam {nama}\n")
else:
    print("jam tidak valid!")

jamKeluarKerja = int(input("Jam keluar kerja: "))

if jamKeluarKerja >=6 and jamKeluarKerja <= 12:
    print(f"selamat pagi")

elif jamKeluarKerja >= 12 and jamKeluarKerja <= 15 :
    print(f"selamat siang")

elif jamKeluarKerja >= 15 and jamKeluarKerja <= 18:
    print(f"selamat sore")

elif jamKeluarKerja >= 18 and jamKeluarKerja <= 24:
    print(f"selamat malam")
else:
    print("Jam tidak valid!")

print(5*"-","rincian gaji",5*"-")

print(f"Nama : {nama}")

waktuKerja = jamKeluarKerja - jamKerja

print(f"Waktu Kerja = {waktuKerja} jam ({jamKerja} s.d {jamKeluarKerja})")

if waktuKerja <= 8:
    gaji_total = gajiPerhari
else:
    gaji_tambahan = (waktuKerja - 8) * 15000
    gaji_total = gajiPerhari + gaji_tambahan

print(f"Gaji perhari : {gajiPerhari}")
print(f"Lembur : {gaji_total} ({waktuKerja} * Rp.15,000)")